# Generated by Django 5.1 on 2024-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, help_text='Ingrese hashtags separados por comas', max_length=200),
        ),
    ]
